FoodMaster/food/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^list$', views.list_foods, name="list_foods"),
    url(r'^new$', views.new_food, name="new_food"),
    url(r'^input$', views.food_input, name="food_input"),
]

FoodMaster/portion/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^list$', views.list_portions, name="list_portions"),
    url(r'^new$', views.new_portion, name="new_portion"),
]

FoodMaster/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .user import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^food/', include('FoodMaster.food.urls')),
    url(r'^portion/', include('FoodMaster.portion.urls')),
    url(r'^user/', include('FoodMaster.user.urls')),
    url(r'^$', views.home, name="home"),
]

FoodMaster/user/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^register$', views.register, name="register"),
    url(r'^login$', views.login, name="login"),
    url(r'^logout$', views.logout_user, name="logout"),
    url(r'^(?P<username>.*)$', views.profile, name="profile"),
]

FoodMaster/food/models.py
from django.db import models

# Create your models here.
class Food(models.Model):

    name = models.CharField(max_length=128)
    kcal = models.FloatField()
    carb = models.FloatField()
    protein = models.FloatField()
    fat = models.FloatField()

    def __str__(self):
        return "{name},{kcal},{carb},{protein},{fat}".format(name=self.name,
                                                             kcal=self.kcal,
                                                             carb=self.carb,
                                                             protein=self.protein,
                                                             fat=self.fat)

FoodMaster/portion/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
from django.db import models

from FoodMaster.food.models import Food

# Create your models here.
class Portion(models.Model):

    user = models.ForeignKey(User)
    food = models.ForeignKey(Food)
    amount = models.FloatField()
    date = models.DateTimeField(auto_now_add=True)

FoodMaster/user/models.py
from django.db import models

# Create your models here.

FoodMaster/user/forms.py
import string
import random

from django import forms
from django.contrib.auth.models import User


class RegisterForm(forms.Form):
    first_name = forms.CharField(required=True, widget=forms.TextInput())
    last_name = forms.CharField(required=True, widget=forms.TextInput())
    email = forms.EmailField(required=True, widget=forms.TextInput())
    username = forms.CharField(required=True, widget=forms.TextInput())
    password = forms.CharField(required=True, widget=forms.PasswordInput())
    confirm_password = forms.CharField(required=True, widget=forms.PasswordInput())

    def clean_email(self):

        email = self.cleaned_data.get('email')
        check_email = User.objects.filter(email=email)

        if check_email:
            raise forms.ValidationError(
                "A user associated with this email address already exists")

        return email

    def clean_password(self):
        print(self.cleaned_data)
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        print(password,confirm_password)
        # if not password == confirm_password:
        #     raise forms.ValidationError("Password mismatch")
        #
        # elif len(password) < 6:
        #     raise forms.ValidationError("Password is too short (6 symbols)")
        #
        # elif password.isalpha() or password.isdigit():
        #     raise forms.ValidationError("Password should contain at least one alphabetic and one non-alphabetic character")

        return password

    def save(self):

        data = self.cleaned_data

        new_user = User.objects.create_user(
            username=data['username'],
            first_name=data['first_name'],
            last_name=data['last_name'],
            email=data['email'],
            password=data['password'],
            )

        return new_user

FoodMaster/food/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect

from FoodMaster.food.models import Food


# Create your views here.
def list_foods(request):
    foods = Food.objects.all()
    return render(request, "food/list_foods.html", {"foods": foods})

def new_food(request):
    # Adding new food to the list with foods
    if request.method == "POST":
        food_record = { k: v for k, v in request.POST.items() if k != "csrfmiddlewaretoken"}
        print("THIS ONE!!!",request.POST["name"])

        Food.objects.create(**food_record)

        return render(request, "food/new_food.html", {"message": "New food has been added!"})

    return render(request, "food/new_food.html", {})


def food_input(request):
    # Autocomplete function
    if request.method == "GET":
        mathing_food_objects = Food.objects.filter(name__contains=request.GET.get("lookFor",None))
        matching_food_names = [x.name for x in mathing_food_objects]
        matching_food_nutritions = [[x.kcal, x.carb, x.protein, x.fat] for x in mathing_food_objects]

    return JsonResponse({'foods': matching_food_names,
                         'nutritions': matching_food_nutritions})

FoodMaster/portion/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect

from FoodMaster.portion.models import Portion
from FoodMaster.food.models import Food


# Create your views here.
def list_portions(request):
    portions = Portion.objects.filter(user=request.user).select_related()
    return render(request, "portion/list_portions.html", {"portions": portions})

def new_portion(request):
    # Adding new portion to the list with portions
    if request.method == "POST":
        food = Food.objects.get(name=request.POST["name"])
        Portion.objects.create(user=request.user, food=food, amount=request.POST["amount"])

        return render(request, "portion/new_portion.html", {"message": "New portion has been added!"})

    return render(request, "portion/new_portion.html", {})

FoodMaster/user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import logout, authenticate
from django.contrib.auth import login as auth_login

from FoodMaster.portion.models import Portion
from FoodMaster.user.forms import RegisterForm


# Create your views here.
def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        print("confirm_password", request.POST.get("confirm_password"))
        if form.is_valid():
            #data = form.cleaned_data
            form.save()
            return render(request, "user/register.html", {"message": "Your registration is successful!"})
    else:
        form = RegisterForm()
    return render(request, 'user/register.html', {'form': form})

def login(request):
    if request.method == "POST":
        message = ""
        user = authenticate(
            username=request.POST.get("username"),
            password=request.POST.get("password"))

        if user:
            auth_login(request, user)
            # message = "Welcome, nerdy birdy!"
        else:
            message = "Something went wrong!"
            return render(request, "user/login.html", {"message": message})

        return redirect('home')

    return render(request, "user/login.html", {})

def logout_user(request):
    logout(request)
    return redirect('home')

def home(request):
    # This what we do on Home page
    message = "Hello, {name}!"
    user = request.user

    if user.is_authenticated():
        name = user.first_name
    else:
        name = "stranger"

    message = message.format(name=name)
    return render(request, "home.html", {"greeting_message": message})

def profile(request, username):
    portions = list(Portion.objects.filter(user__username=username).select_related())
    user = portions[0].user

    return render(request, "user/profile.html", {"user": user, "portions": portions})

templates/food/list_foods.html
{% extends "master.html" %}

{% block title %}
    Food Master | List foods
{% endblock title %}

{% block stylesheets %}
{% endblock stylesheets %}

{% block content %}
Table of all foods.. <br/>

<table>
    <thead>
        <th>Food name</th>
        <th>kcal</th>
        <th>carb</th>
        <th>protein</th>
        <th>fat</th>
    </thead>
    <tbody>
        {% for food in foods %}
        <tr>
            <td> {{ food.name }} </td>
            <td> {{ food.kcal }} </td>
            <td> {{ food.carb }} </td>
            <td> {{ food.protein }} </td>
            <td> {{ food.fat }} </td>
        </tr>
        {% endfor %}
    </tbody>

</table>


{% endblock content %}


{% block scripts %}
{% endblock scripts %}

templates/food/new_food.html
{% extends "master.html" %}

{% block title %}
    Food Master | New food
{% endblock title %}

{% block stylesheets %}
{% endblock stylesheets %}


{% block content %}

{{ message }}

<form method="POST" action="{% url 'new_food' %}">
    {% csrf_token %}
    Food name:<br/>
    <input type="text" name="name" id="name"><br/>
    Food kcal:<br/>
    <input type="text" name="kcal"><br/>
    Food carb:<br/>
    <input type="text" name="carb"><br/>
    Food protein:<br/>
    <input type="text" name="protein"><br/>
    Food fat:<br/>
    <input type="text" name="fat"><br/><br/>
    <input type="submit" name="" value="Send">
</form>

{% endblock content %}


{% block scripts %}
{% endblock scripts %}

templates/home.html
{% extends "master.html" %}

{% block title %}
    Food Master | Home
{% endblock title %}

{% block stylesheets %}
{% endblock stylesheets %}

{% block content %}

    {{ greeting_message }}

{% endblock content %}


{% block scripts %}
{% endblock scripts %}

templates/master.html
<!DOCTYPE html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block title %}{% endblock title %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">
        <meta name="robots" content="noindex">
        <!--CSS block-->
        <link rel="shortcut icon" href="{{ STATIC_URL }}img/favicon.ico" />
        <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css">

        <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
        {% block stylesheets %}

        {% endblock stylesheets %}

    </head>
    <body>
        <!-- Header -->
        <header>
            <ul>

                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                    <li><a href="{% url 'new_food' %}">Add new food</a></li>
                    <li><a href="#">Delete food</a></li>
                    <li><a href="{% url 'list_foods' %}">List all foods</a></li>
                    <li><a href="{% url 'new_portion' %}">Add new portion</a></li>
                    <li><a href="{% url 'list_portions' %}">List all portions</a></li>

                {% else %}
                    <li><a href="{% url 'register' %}">Register</a></li>
                    <li><a href="{% url 'login' %}">Login</a></li>
                {% endif %}
            </ul>
        </header>
        <!-- Content -->
        <div id="content">
            {% block content %}

            {% endblock content %}
        </div>
        <!-- Footer -->
         <footer>
            Aloha!
         </footer>

    <!-- Script block -->
    <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script src="{{STATIC_URL}}js/EliScript.js"></script>

    {% block scripts %}
    {% endblock scripts %}
    </body>
</html>

templates/portion/list_portions.html
{% extends "master.html" %}

{% block title %}
    Food Master | List portions
{% endblock title %}

{% block stylesheets %}
{% endblock stylesheets %}

{% block content %}
Table of all portions.. <br/>

<table>
    <thead>
        <th>Date</th>
        <th>Food name</th>
        <th>Amount</th>
        <th>kcal</th>
        <th>carb</th>
        <th>protein</th>
        <th>fat</th>
    </thead>
    <tbody>
        {% for portion in portions %}
        <tr>
            <td> {{ portion.date }} </td>
            <td> {{ portion.food.name }} </td>
            <td> {{ portion.name }} </td>
            <td> {{ portion.food.kcal }} </td>
            <td> {{ portion.food.carb }} </td>
            <td> {{ portion.food.protein }} </td>
            <td> {{ portion.food.fat }} </td>
        </tr>
        {% endfor %}
    </tbody>

</table>


{% endblock content %}


{% block scripts %}
{% endblock scripts %}

templates/portion/new_portion.html
{% extends "master.html" %}

{% block title %}
    Food Master | New portion
{% endblock title %}

{% block stylesheets %}
{% endblock stylesheets %}


{% block content %}

{{ message }}

<form method="POST" action="{% url 'new_portion' %}">
    {% csrf_token %}
    Food name:<br/>
    <input type="text" name="name" id="name" data-url="{% url 'food_input' %}"><br/>
    Food amount:<br/>
    <input type="text" name="amount"><br/>
    <br/><br/>
    <input type="submit" name="" value="Send">
</form>

{% endblock content %}


{% block scripts %}
<script>
    autocomplete_food(el="#name",url=$("#name").data("url"));
</script>
{% endblock scripts %}

templates/user/login.html
{% extends "master.html" %}

{% block title %}
    Food Master | Login
{% endblock title %}

{% block stylesheets %}
{% endblock stylesheets %}


{% block content %}

{{ message }}

<form method="POST" action="{% url 'login' %}">
    {% csrf_token %}
    Username:<br/>
    <input type="text" name="username"><br/>
    Password:<br/>
    <input type="password" name="password"><br/>
    <br/><br/>
    <input type="submit" name="" value="Login">
</form>

{% endblock content %}


{% block scripts %}

{% endblock scripts %}

templates/user/profile.html
{% extends "master.html" %}

{% block title %}
    Food Master | {{ user.username }} profile
{% endblock title %}

{% block stylesheets %}
{% endblock stylesheets %}

{% block content %}

    This is the profile of {{ user.first_name }} {{ user.last_name }}.<br/>
    Table of their portions.. <br/>

    <table>
        <thead>
            <th>Date</th>
            <th>Food name</th>
            <th>Amount</th>
            <th>kcal</th>
            <th>carb</th>
            <th>protein</th>
            <th>fat</th>
        </thead>
        <tbody>
            {% for portion in portions %}
            <tr>
                <td> {{ portion.date }} </td>
                <td> {{ portion.food.name }} </td>
                <td> {{ portion.name }} </td>
                <td> {{ portion.food.kcal }} </td>
                <td> {{ portion.food.carb }} </td>
                <td> {{ portion.food.protein }} </td>
                <td> {{ portion.food.fat }} </td>
            </tr>
            {% endfor %}
        </tbody>

    </table>

{% endblock content %}


{% block scripts %}
{% endblock scripts %}

templates/user/register.html
{% extends "master.html" %}

{% block title %}
    Food Master | Register
{% endblock title %}

{% block stylesheets %}
{% endblock stylesheets %}


{% block content %}

{{ message }}

<form method="POST" action="{% url 'register' %}">
    {% csrf_token %}

    <ul>
        <li><label for="id_first_name" class="main_label">
            {% if form.first_name.errors %}
                {{ form.first_name.errors }}
            {% endif %}
            First name:</label>
        </li>
        <li>
            {{ form.first_name }}
        </li>
        <li><label for="" class="main_label">
            {% if form.last_name.errors %}
                {{ form.last_name.errors }}
            {% endif %}
            Last name:</label>
        </li>
        <li>
            {{ form.last_name }}
        </li>
        <li><label for="" class="main_label">
            {% if form.email.errors %}
                {{ form.email.errors }}
            {% endif %}
            Email:</label>
        </li>
        <li>
            {{ form.email }}
        </li>
        <li><label for="" class="main_label">
            {% if form.username.errors %}
                {{ form.username.errors }}
            {% endif %}
            Username:</label>
        </li>
        <li>
            {{ form.username }}
        </li>
        <li><label for="" class="main_label">
            {% if form.password.errors %}
                {{ form.password.errors }}
            {% endif %}
            Password:</label>
        </li>
        <li>
            {{ form.password }}
        </li>
        <li><label for="" class="main_label">
            {% if form.confirm_password.errors %}
                {{ form.confirm_password.errors }}
            {% endif %}
            Confirm Password:</label>
        </li>
        <li>
            {{ form.confirm_password }}
        </li>
    </ul>
    <input type="submit" name="" value="Register">
</form>

{% endblock content %}


{% block scripts %}

{% endblock scripts %}